# _config.yml
name:         Jonathan Chen / UI &amp; UX Designer
description:  My Personal Site

baseurl:      http://jonathanc.com
permalink:    pretty
exclude:      ["CNAME", "README.md", "Gemfile", "Gemfile.lock"]