# _config.yml
name:         Jonathan Chen / UI &amp; UX Designer
description:  My Personal Site

baseurl:      https://jonathanc.com
permalink:    pretty
exclude:      [".gitignore", "CNAME", "README.md", "Gemfile", "Gemfile.lock", "node_modules", "sass", "config.rb", "package.json", "package-lock.json"]